### ISSUE TITLE
Media corruption 

### ISSUE THREAD

**Issue by dracoqcca** [Hitcher/skin.ftv#1]
Hi HitcherUK,

you seems to have another coruption in you media folder see media/home/home_button_nf.png

**Comment by Hitcher** [comment]
And DefaultMusicRoles.png as they were both recently added.

I give up as I have no idea why GitHub is doing this to new/updated images.

**Comment by Hitcher** [comment]
Managed to fix DefaultMusicRoles.png by drag and dropping it directly in my browser but it's not working for home_button_nf.png. The file is fine my end it just gets messed up pushing to GitHub.

EDIT: @dracoqcca It seems OK now. Can you check please?

**Comment by dracoqcca** [comment]
Yes seems to be ok now thanks! You may think to use a compile version to github maybe?

**Comment by Hitcher** [comment]
Submission to the official repo must be in this format and not a textures.xbt.
